### ISSUE TITLE
Where is the MSRVTT json file in CLIP-ViP?

### ISSUE THREAD

**Issue by justopit** [microsoft/XPretrain#11]
Hi, I found that in your msrvvt_config, train9k.jsonl and test1ka.jsonl are needed. But I don't find anything about it in your readme.md. Are they in the hdvila_ofa_captions_db? If the jsonl files are in the folder, How should we open the 'data.db' in the folder.

**Comment by justopit** [comment]
I found it in HD-VILA

**Comment by wangpichao** [comment]
> I found it in HD-VILA

Could you please send the link? I can not find it. Could it directly be downloaded? Thank you.
