### ISSUE TITLE
About OFA-Caption generated captions on HD-VILA-100M

### ISSUE THREAD

**Issue by yuqi657** [microsoft/XPretrain#14]
First of all, thanks for your interesting work.

May I ask where can I get the OFA-Caption generated captions on HD-VILA-100M in your work?

**Comment by HellwayXue** [comment]
Hi, the link can be found at README.md in CLIP-ViP folder:
[https://hdvila.blob.core.windows.net/dataset/hdvila_ofa_captions_db.zip?sp=r&st=2023-03-16T04:58:26Z&se=2026-03-01T12:58:26Z&spr=https&sv=2021-12-02&sr=b&sig=EYE%2Bj11VWfQ6G5dZ8CKlOOpL3ckmmNqpAtUgBy3OGDM%3D](OFA-Caption url)

**Comment by HellwayXue** [comment]
Hi, the link is: [OFA-Captions Link](https://hdvila.blob.core.windows.net/dataset/hdvila_ofa_captions_db.zip?sp=r&st=2023-03-16T04:58:26Z&se=2026-03-01T12:58:26Z&spr=https&sv=2021-12-02&sr=b&sig=EYE%2Bj11VWfQ6G5dZ8CKlOOpL3ckmmNqpAtUgBy3OGDM%3D), which can also be found at README.md in CLIP-ViP folder.
