### ISSUE TITLE
Video compression/decoding methods of each dataset in CLIP-ViP

### ISSUE THREAD

**Issue by fadzaka12** [microsoft/XPretrain#17]
Hi, I'm trying to reproduce the CLIP-ViP result. In the readme file, it is mentioned that the data preprocessing step follows HD-VILA. However, in the [configuration files](https://github.com/microsoft/XPretrain/tree/main/CLIP-ViP/src/configs) of the downstream task, it seems the compression/decoding method is different from [these](https://github.com/microsoft/XPretrain/tree/main/hd-vila/src/configs). Are these video preprocessing method correct:
- MSR-VTT: compression, 6 FPS
- LSMDC: no compression/decoding, use raw video as is
- ActivityNet: decoding lr
- DiDeMo: compression, X FPS (What is the number of X? Is it 6 too?)

**Comment by HellwayXue** [comment]
Hi, your listed preprocessing methods are right. For DiDeMo, we keep 32 frames for each video thus the fps is variable.
