### ISSUE TITLE
Ways to open the .mdb caption files 

### ISSUE THREAD

**Issue by ffnc1020** [microsoft/XPretrain#19]
Is there an easy way to open the .mdb files? Trying to dump it to csv with mdbtools but it complains the file is not an access database.

**Comment by HellwayXue** [comment]
Sorry, I'm unfamiliar with the mdbtools. We use the python package lmdb to open and load data. So at least you can also use lmdb to enumerate the entries and dump to a CSV file. This might take a while, but should work.

**Comment by ffnc1020** [comment]
Thanks for the tip! I was able to read the captions with lmdb.
