### ISSUE TITLE
HD-VILA-100M dataset, where is the text corresponding to each video?

### ISSUE THREAD

**Issue by Qiliqing** [microsoft/XPretrain#2]
Hi, @bei21 @msftdata 

Thank you for your great paper.

I downloaded and decompressed the "hdvila100m.zip", but could not find the transcriptions corresponding to each video.

Did I miss something?
Could you let me know how to get the transcriptions?
Thank you.

**Comment by dome272** [comment]
Hey there,
great work you started!
Are there any updates on how to also download the annotations? I see there is a script for downloading the videos, but what about the corresponding text?
