### ISSUE TITLE
MSR-VTT fine tune epochs number

### ISSUE THREAD

**Issue by ffnc1020** [microsoft/XPretrain#21]
Can you help clarify what's the actual fine-tune epoch used for MSR-VTT dataset? In the paper it says 5 epochs is used (which is the common setting), however in the config file [here](https://github.com/microsoft/XPretrain/blob/5318f2ae399c58c83d9dd605b425905882926d14/CLIP-ViP/src/configs/msrvtt_retrieval/msrvtt_retrieval_vip_base_32.json#L72) , it says 100?

**Comment by HellwayXue** [comment]
There are 20 sentences for each video in MSR-VTT, as our implementation samples one sentence in each iteration, we set epoch=100 in the config to reach the actual epoch=5.

**Comment by ffnc1020** [comment]
Thanks for the clarification!
