### ISSUE TITLE
where are the train9k.jsonl and test1ka.jsonl files in MSRVTT retrieval? 

### ISSUE THREAD

**Issue by wangpichao** [microsoft/XPretrain#25]
I notice that we need train9k.jsonl and test1ka.jsonl files in MSRVTT retrieval task, but the only .csv files are provided in original annotations.  Thus, where could I find or generate these two files?

**Comment by HellwayXue** [comment]
Hi, please refer to the data preparison part in [here](https://github.com/microsoft/XPretrain/tree/main/hd-vila). [This script](https://github.com/microsoft/XPretrain/blob/main/hd-vila/scripts/download_data.sh) will download the annotations for all downstream tasks.

**Comment by wangpichao** [comment]
> Hi, please refer to the data preparison part in [here](https://github.com/microsoft/XPretrain/tree/main/hd-vila). [This script](https://github.com/microsoft/XPretrain/blob/main/hd-vila/scripts/download_data.sh) will download the annotations for all downstream tasks.

Got it and thank you very much.

**Comment by wangpichao** [comment]
use script to download the files.
