### ISSUE TITLE
Questions about HD-VILA

### ISSUE THREAD

**Issue by HenryHZY** [microsoft/XPretrain#3]
Hi @bei21 @TiankaiHang , I would like to ask some questions about HD-VILA.
1. How large are the HD-VILA video files and subtitle files respectively? I guess there are at least 10TB or above. Are you using SSD to store them?
2. It is mentioned in the paper that 64 V100 GPUs are required. How much time does it take for pre-training stage1, pre-training stage2 and downstream tasks respectively?
3. Do you have a plan to share the code of HD-VILA?
Thank you very much!

**Comment by TiankaiHang** [comment]
Thanks for your attention! :-)

1. The storage for HD-VILA video files and subtitle files are 250T and 27G, respectively. The compressed version with 240p and 3 FPS is 50T. Actually, they are more than 10TB, we store them in Microsoft Azure Storage.
2. For pre-training stage 1, we train 6 epochs for 12 days (low resolution), 1 epoch for 6 days (high resolution). For pre-training stage 2, it takes 7 days to train 3 epochs (low resolution). For downstream tasks, it takes < 1 day for finetuning on 8 V100 GPUs.
3. Of course, we will release the code. The code has been prepared and is waiting for company's approval.

Best.

**Comment by HenryHZY** [comment]
@TiankaiHang 
Thanks for your quick reply!
I believe that HD-VILA will be impactful in Video-Language Pre-training. 
Looking forward to your training code and data processing code:)

**Comment by SCZwangxiao** [comment]
> 1. we store them in Microsoft Azure Storage

Since the dataset is stored in Microsoft Azure Storage, Maybe you could put them in object storage for users to download? Downloading and processing videos from youtube is quite a hard job.

**Comment by bei21** [comment]
> 

Due to copyright issues, we cannot make the videos public. Sorry about that.
