### ISSUE TITLE
releasing code and pretrain

### ISSUE THREAD

**Issue by maralzar** [microsoft/XPretrain#5]
Hi thank you for your interesting work when will you release the code and pre-train model  CLIP-ViP repository?

**Comment by HellwayXue** [comment]
Hi, our paper is under review, we will release code after the notification. Thanks for your patience.

**Comment by e-bug** [comment]
Congratulations on the ICLR acceptance! 
Can you provide an ETA for the release of CLIP-ViP code and weights?
Thank you :)

**Comment by HellwayXue** [comment]
Hi, the code and model weights are ready. Per the company's policy, there are still several procedures to go through before release. Please stay tuned.
