### ISSUE TITLE
Code for transcript text processing

### ISSUE THREAD

**Issue by RyanMarten** [microsoft/XPretrain#6]
Thanks for releasing this great dataset!

Could you please kindly release the transcript text processing code as mentioned by @bei21? 

As discussed in the previous comment: https://github.com/microsoft/XPretrain/issues/2#issuecomment-1170920729, the text itself can't be released.

**Comment by bei21** [comment]
Resolved by email.

**Comment by PeisenZhao** [comment]
@bei21 
As you mentioned it is solved by email. Could you please send me the transcript text processing code?
pszhao93@gmail.com
Thanks!

**Comment by SCZwangxiao** [comment]
> Resolved by email.

May I also request the transcript text processing code? Although you've mentioned the prosedures in the paper, I think it would be better to use the same ASR preprocessing code.
scz.wangxiao@gmail.com
Thanks!

**Comment by fhlt** [comment]
May I also request the transcript text processing code?
liang0305tao@gmail.com
Thanks!

**Comment by klaus2015** [comment]
May I also request the hd-vila-100m text processing code?
598467866@qq.com
Thanks!

**Comment by lizhengwei1992** [comment]
@bei21 , I have downloaded the video data and also need to download the corresponding textual description data. Thank you very much! 
lzw1992_work@163.com

**Comment by bei21** [comment]
@lizhengwei1992 @klaus2015 @fhlt Please drop me an email about the transcript issue. Thanks.

**Comment by jhj7905** [comment]
@bei21 
May I also request the hd-vila-100m text processing code?
jhj7905@naver.com
thank you

**Comment by bei21** [comment]
@jhj7905 Please drop me an email about the transcript issue. Thanks.

**Comment by jhj7905** [comment]
Hello
May i also request the hd-vila-100m text processing code?
Thank u in advance
-----Original Message-----

**Comment by zyyyz** [comment]
May I also request the transcript text processing code? 
zhouyuan2016@gmail.com
Thank you very much!

**Comment by bei21** [comment]
@shibin1027 @zyyyz Please email me with your request and I will reply in time. Thanks!

**Comment by qazimbhat1** [comment]
May I also request the hd-vila-100m text processing code?
mohammad.bhat@mbzuai.ac.ae

**Comment by wwyy1234** [comment]
> @shibin1027 @zyyyz Please email me with your request and I will reply in time. Thanks!

May I also request the transcript text processing code?
1695084647@qq.com
Thank you very much!

**Comment by ChangyaoTian** [comment]
Hi, may I also request the transcript text processing code? @bei21 
[tcyhost@link.cuhk.edu.hk](tcyhost@link.cuhk.edu.hk)
Thanks a lot!

**Comment by canqin001** [comment]
Hi, @bei21 may I request the transcript text processing code?
qin.ca@northeastern.edu
Thank you so much!

**Comment by howellyoung-s** [comment]
Hi, @bei21, could you kindly share the transcript text processing code with me?
monkeyhey150027@126.com
Thanks!!

**Comment by xpwu95** [comment]
May I also request the transcript text processing code?
[xpwu95@163.com](mailto:xpwu95@163.com)
Thanks!

**Comment by zhanzhibingshang** [comment]
Hi, @bei21 , May I also request the transcript text processing code?
15659812869@163.com
Thanks!

**Comment by antonschafer** [comment]
Hi @bei21 , could you share the transcript text processing code with me please?
scanton@ethz.ch
Thanks in advance!!

**Comment by sunwhw** [comment]
could you also share the transcript text processing code with me please? Thanks ! 837793693@qq.com

**Comment by BingliangLi** [comment]
May I also request the hd-vila-100m text processing code?

bingliangli@link.cuhk.edu.cn
Thanks!

**Comment by GXYM** [comment]
could you also share the transcript text processing code with me please? Thanks ! [837793693@qq.com](mailto:anoy2019cvpr@gmail.com)

**Comment by 630bdd** [comment]
Hi @bei21 , could you also share the transcript text processing code with me please? 

630bdd@gmail.com
Thanks!

**Comment by YTY101** [comment]
Hi @bei21, could you also send me the transcript text processing code please?

y0115821005@gmail.com
Thanks!

**Comment by YingYellow** [comment]
Hi @bei21 , could you also send me the transcript text processing code please?

yinghuang230@gmail.com
Thanks!

**Comment by kevinschaul** [comment]
Hi @bei21, could you also send me the transcript text processing code please?

[kevin.schaul@gmail.com](mailto:kevin.schaul@gmail.com)
Thanks!

**Comment by Arsiuuu** [comment]
Hi @bei21 , could you also send me the transcript text processing code please?

eurekajtx@gmai.com

Thanks!

**Comment by Mael-zys** [comment]
Hi @bei21 , could you also send me the transcript text processing code please?

[yangsong.zhang.zys@gmail.com](mailto:yangsong.zhang.zys@gmail.com)

Thanks!
